from store.models import Wishlist


def language_context(request):
    supported = {
        'uz': {
            'lang_code': 'uz',
            'language_menu': 'Til: UZB',
            'current_language': "O'zbekcha",
            'nav_home': 'Bosh sahifa',
            'nav_cart': 'Savat',
            'nav_orders': 'Buyurtmalar',
            'nav_wishlist': 'Sevimlilar',
            'nav_logout': 'Chiqish',
            'nav_login': 'Kirish',
            'nav_register': "Ro'yxatdan o'tish",
            'footer_copy': '&copy; 2026 BookHub. Barcha huquqlar himoyalangan.',
            'login_title': 'Kirish',
            'login_subtitle': "Hisobingizga kirish uchun ma'lumotlaringizni kiriting",
            'login_button': 'Kirish',
            'login_no_account': "Agar hisobingiz yo‘q bo‘lsa,",
            'login_register_link': "Ro‘yxatdan o‘ting",
            'register_title': "Ro‘yxatdan o‘tish",
            'register_button': "Ro‘yxatdan o‘tish",
            'register_have_account': 'Hisobingiz bormi?',
            'register_login_link': 'Kirish',
            'cart_title': 'Savat',
            'cart_book': 'Kitob',
            'cart_quantity': 'Miqdor',
            'cart_price': 'Narxi',
            'cart_total': 'Jami',
            'cart_remove': 'O‘chirish',
            'cart_checkout': "To'lovga o'tish",
            'cart_empty_title': 'Savatda hech narsa yo‘q',
            'cart_empty_text': 'Siz hozircha hech qanday kitob qo‘shmagansiz. Kitoblar sahifasiga qaytib davomini tanlang.',
            'cart_empty_action': 'Kitoblar sahifasiga qaytish',
            'checkout_title': "To'lov",
            'checkout_book': 'Kitob',
            'checkout_quantity': 'Miqdor',
            'checkout_unit_price': 'Birlik narxi',
            'checkout_total': 'Jami',
            'checkout_finish': 'Buyurtmani yakunlash',
            'checkout_empty': 'Savat bo‘sh.',
            'success_title': 'Buyurtma qabul qilindi',
            'success_text': 'Buyurtmangiz muvaffaqiyatli qabul qilindi. Siz buyurtma tarixini ko‘rishingiz mumkin.',
            'success_orders_button': 'Buyurtmalarim',
            'home_heading': 'Eng yaxshi kitoblarni toping',
            'home_search_placeholder': "Kitob nomi yoki muallif...",
            'home_search_button': 'Qidirish',
            'home_feature_heading': 'Tanlangan kitoblar',
            'home_feature_subtitle': 'Janr bo‘yicha eng yaxshi kitoblar',
            'home_categories': 'Bo‘limlar',
            'home_all': 'Barchasi',
            'home_no_books': 'Hech qanday kitob topilmadi.',
            'home_no_books_text': 'So‘rovingizga mos kitob topilmadi. Boshqa atamalar bilan qidirib ko‘ring.',
            'book_breadcrumb_home': 'Bosh sahifa',
            'book_author': 'Muallif',
            'book_section': "Bo'limi",
            'book_price': 'Narxi',
            'book_stock': 'Ombor',
            'book_in_stock': 'Mavjud',
            'book_out_of_stock': 'Tugagan',
            'book_description': 'Tavsifi',
            'book_add_to_cart': "Savatga qo'shish",
            'book_sold_out': 'Mahsulot tugagan',
            'book_back': 'Orqaga qaytish',
            'book_related': "Shunga O'xshash Kitoblar",
            'book_view': "Ko'rish",
            'order_history_title': 'Mening buyurtmalarim',
            'order_history_subtitle': 'Sizning oxirgi buyurtmalaringiz shu yerda ko‘rinadi.',
            'order_status': 'Status',
            'order_total_text': 'Jami',
            'order_none': 'Sizda hozircha buyurtma yo‘q.',
            'order_history_empty_text': 'Hozircha buyurtmangiz yo‘q. Sevimli kitoblaringizni tanlang va buyurtma qiling.',
            'order_detail_status': 'Status',
            'order_detail_time': 'Vaqti',
            'order_detail_quantity': 'Miqdor',
            'order_detail_unit_price': 'Birlik narxi',
            'order_detail_sum': 'Jami',
            'order_detail_summary': 'Buyurtma summasi',
        },
        'ru': {
            'lang_code': 'ru',
            'language_menu': 'Язык: RU',
            'current_language': 'Русский',
            'nav_home': 'Главная',
            'nav_cart': 'Корзина',
            'nav_orders': 'Заказы',
            'nav_wishlist': 'Избранное',
            'nav_logout': 'Выйти',
            'nav_login': 'Войти',
            'nav_register': 'Регистрация',
            'footer_copy': '&copy; 2026 BookHub. Все права защищены.',
            'login_title': 'Вход',
            'login_subtitle': 'Введите данные для доступа к аккаунту',
            'login_button': 'Войти',
            'login_no_account': 'Если у вас нет аккаунта,',
            'login_register_link': 'зарегистрируйтесь',
            'register_title': 'Регистрация',
            'register_button': 'Зарегистрироваться',
            'register_have_account': 'Уже есть аккаунт?',
            'register_login_link': 'Войти',
            'cart_title': 'Корзина',
            'cart_book': 'Книга',
            'cart_quantity': 'Количество',
            'cart_price': 'Цена',
            'cart_total': 'Итого',
            'cart_remove': 'Удалить',
            'cart_checkout': 'Оформить заказ',
            'cart_empty_title': 'Корзина пуста',
            'cart_empty_text': 'Вы пока не добавили ни одной книги. Вернитесь на страницу книг и выберите.',
            'cart_empty_action': 'Вернуться к книгам',
            'checkout_title': 'Оплата',
            'checkout_book': 'Книга',
            'checkout_quantity': 'Количество',
            'checkout_unit_price': 'Цена за единицу',
            'checkout_total': 'Итого',
            'checkout_finish': 'Завершить заказ',
            'checkout_empty': 'Корзина пуста.',
            'success_title': 'Заказ принят',
            'success_text': 'Ваш заказ успешно принят. Вы можете просмотреть историю заказов.',
            'success_orders_button': 'Мои заказы',
            'home_heading': 'Найдите лучшие книги',
            'home_search_placeholder': 'Название книги или автор...',
            'home_search_button': 'Поиск',
            'home_feature_heading': 'Избранные книги',
            'home_feature_subtitle': 'Лучшие книги по жанрам',
            'home_categories': 'Категории',
            'home_all': 'Все',
            'home_no_books': 'Ничего не найдено.',
            'home_no_books_text': 'По вашему запросу не найдено ни одной книги. Попробуйте другие ключевые слова.',
            'book_breadcrumb_home': 'Главная',
            'book_author': 'Автор',
            'book_section': 'Раздел',
            'book_price': 'Цена',
            'book_stock': 'Наличие',
            'book_in_stock': 'В наличии',
            'book_out_of_stock': 'Закончился',
            'book_description': 'Описание',
            'book_add_to_cart': 'Добавить в корзину',
            'book_sold_out': 'Товар закончился',
            'book_back': 'Вернуться назад',
            'book_related': 'Похожие книги',
            'book_view': 'Посмотреть',
            'order_history_title': 'Мои заказы',
            'order_history_subtitle': 'Здесь отображаются ваши последние заказы.',
            'order_status': 'Статус',
            'order_total_text': 'Итого',
            'order_none': 'У вас пока нет заказов.',
            'order_history_empty_text': 'Пока у вас нет заказов. Выберите книги и оформите первый заказ.',
            'order_detail_status': 'Статус',
            'order_detail_time': 'Время',
            'order_detail_quantity': 'Количество',
            'order_detail_unit_price': 'Цена за единицу',
            'order_detail_sum': 'Итого',
            'order_detail_summary': 'Сумма заказа',
        },
        'en': {
            'lang_code': 'en',
            'language_menu': 'Lang: ENG',
            'current_language': 'English',
            'nav_home': 'Home',
            'nav_cart': 'Cart',
            'nav_orders': 'Orders',
            'nav_wishlist': 'Wishlist',
            'nav_logout': 'Logout',
            'nav_login': 'Login',
            'nav_register': 'Register',
            'footer_copy': '&copy; 2026 BookHub. All rights reserved.',
            'login_title': 'Login',
            'login_subtitle': 'Enter your account details to sign in',
            'login_button': 'Login',
            'login_no_account': 'Don’t have an account?',
            'login_register_link': 'Register now',
            'register_title': 'Register',
            'register_button': 'Create account',
            'register_have_account': 'Already have an account?',
            'register_login_link': 'Login',
            'cart_title': 'Cart',
            'cart_book': 'Book',
            'cart_quantity': 'Quantity',
            'cart_price': 'Price',
            'cart_total': 'Total',
            'cart_remove': 'Remove',
            'cart_checkout': 'Checkout',
            'cart_empty_title': 'Your cart is empty',
            'cart_empty_text': 'You have not added any books yet. Go back to the books page to choose.',
            'cart_empty_action': 'Return to books',
            'checkout_title': 'Checkout',
            'checkout_book': 'Book',
            'checkout_quantity': 'Quantity',
            'checkout_unit_price': 'Unit price',
            'checkout_total': 'Total',
            'checkout_finish': 'Complete order',
            'checkout_empty': 'Your cart is empty.',
            'success_title': 'Order received',
            'success_text': 'Your order has been successfully received. You can view your order history.',
            'success_orders_button': 'My orders',
            'home_heading': 'Find the best books',
            'home_search_placeholder': 'Book title or author...',
            'home_search_button': 'Search',
            'home_feature_heading': 'Featured books',
            'home_feature_subtitle': 'Top books by genre',
            'home_categories': 'Categories',
            'home_all': 'All',
            'home_no_books': 'No books found.',
            'home_no_books_text': 'No books matched your search. Try different keywords.',
            'book_breadcrumb_home': 'Home',
            'book_author': 'Author',
            'book_section': 'Section',
            'book_price': 'Price',
            'book_stock': 'Stock',
            'book_in_stock': 'In stock',
            'book_out_of_stock': 'Out of stock',
            'book_description': 'Description',
            'book_add_to_cart': 'Add to cart',
            'book_sold_out': 'Sold out',
            'book_back': 'Go back',
            'book_related': 'Related books',
            'book_view': 'View',
            'order_history_title': 'My orders',
            'order_history_subtitle': 'Your recent orders are shown here.',
            'order_status': 'Status',
            'order_total_text': 'Total',
            'order_none': 'You do not have any orders yet.',
            'order_history_empty_text': 'You have no orders yet. Pick some favorite books and place your first order.',
            'order_detail_status': 'Status',
            'order_detail_time': 'Time',
            'order_detail_quantity': 'Quantity',
            'order_detail_unit_price': 'Unit price',
            'order_detail_sum': 'Total',
            'order_detail_summary': 'Order total',
        },
    }
    lang = getattr(request, 'language_code', 'uz')
    data = supported.get(lang, supported['uz'])
    return {
        't': data,
        'lang_code': data['lang_code'],
        'current_language': data['current_language'],
        'language_menu': data['language_menu'],
    }

def cart_count(request):
    cart = request.session.get('cart', {})
    try:
        count = sum(int(v) for v in cart.values())
    except (ValueError, TypeError):
        count = 0
    return {'cart_count': count}

def wishlist_count(request):
    if request.user.is_authenticated:
        wishlist, created = Wishlist.objects.get_or_create(user=request.user)
        return {'wishlist_count': wishlist.books.count()}
    return {'wishlist_count': 0}
